import typing as t
from dataclasses import dataclass
from enum import StrEnum

class ItemType(StrEnum):
    COAT = "Coat"
    DRILL = "Drill"
    DRONE = "Drone"
    GLITCH = "Glitch"
    GUN = "Gun"
    HEALTH_NODE = "Health Node"
    HEALTH_NODE_FRAGMENT = "Health Node Fragment"
    KEY = "Key"
    MOVEMENT = "Movement"
    NOTE = "Note"
    POWER_NODE = "Power Node"
    POWER_NODE_FRAGMENT = "Power Node Fragment"
    RANGE_NODE = "Range Node"
    SIZE_NODE = "Size Node"
    TENDRILS = "Tendrils"

@dataclass
class AVItemData:
    name: str
    group_name: str
    progression: bool = False

item_data: t.Tuple[AVItemData] = (
    AVItemData("DataDisruptor", ItemType.GUN),
    AVItemData("DataGrenade", ItemType.GUN),
    AVItemData("FireWall", ItemType.GUN),
    AVItemData("InertialPulse", ItemType.GUN),
    AVItemData("IonBeam", ItemType.GUN),
    AVItemData("LightningGun", ItemType.GUN),
    AVItemData("MultiDisruptor", ItemType.GUN),
    AVItemData("Reflect", ItemType.GUN),
    AVItemData("Shards", ItemType.GUN),
    AVItemData("Swim", ItemType.GUN),
    AVItemData("TriCone", ItemType.GUN),
    AVItemData("Voranj", ItemType.GUN),
    AVItemData("Nova", ItemType.GUN),
    AVItemData("TetheredCharge", ItemType.GUN),
    AVItemData("VerticalSpread", ItemType.GUN),
    AVItemData("WallTrace", ItemType.GUN),
    AVItemData("DistortionField", ItemType.GUN),
	AVItemData("FlameThrower", ItemType.GUN),
	AVItemData("Kilver", ItemType.GUN),
	AVItemData("Scythe", ItemType.GUN),
	AVItemData("FatBeam", ItemType.GUN),
	AVItemData("HeatSeeker", ItemType.GUN),
	AVItemData("WebSlicer", ItemType.GUN),
	AVItemData("AddressDisruptor1", ItemType.GLITCH, True),
	AVItemData("AddressDisruptor2", ItemType.GLITCH, True),
	AVItemData("Drill", ItemType.DRILL, True),
	AVItemData("DroneGun", ItemType.DRONE, True),
	AVItemData("GlitchBomb", ItemType.GLITCH, True),
	AVItemData("Grapple", ItemType.MOVEMENT, True),
	AVItemData("HighJump", ItemType.MOVEMENT, True),
	AVItemData("GlitchTeleport", ItemType.COAT, True),
	AVItemData("BlackCoat", ItemType.COAT, True),
	AVItemData("RedCoat", ItemType.COAT, True),
	AVItemData("BreachSuppressor", ItemType.KEY, True),
	AVItemData("EnhancedLaunch", ItemType.DRONE, True),
	AVItemData("DroneTeleport", ItemType.DRONE, True),
	AVItemData("PasswordTool", ItemType.KEY, True),
	AVItemData("TendrilsTop", ItemType.TENDRILS),
	AVItemData("TendrilsBottom", ItemType.TENDRILS),
	AVItemData("HealthNode1", ItemType.HEALTH_NODE),
	AVItemData("HealthNode2", ItemType.HEALTH_NODE),
	AVItemData("HealthNode3", ItemType.HEALTH_NODE),
	AVItemData("HealthNode4", ItemType.HEALTH_NODE),
	AVItemData("HealthNode5", ItemType.HEALTH_NODE),
	AVItemData("HealthNode6", ItemType.HEALTH_NODE),
	AVItemData("HealthNode7", ItemType.HEALTH_NODE),
	AVItemData("HealthNode8", ItemType.HEALTH_NODE),
	AVItemData("HealthNode9", ItemType.HEALTH_NODE),
	AVItemData("HealthNode10", ItemType.HEALTH_NODE),
	AVItemData("PowerNode1", ItemType.POWER_NODE),
	AVItemData("PowerNode2", ItemType.POWER_NODE),
	AVItemData("PowerNode3", ItemType.POWER_NODE),
	AVItemData("PowerNode4", ItemType.POWER_NODE),
	AVItemData("PowerNode5", ItemType.POWER_NODE),
	AVItemData("PowerNode6", ItemType.POWER_NODE),
	AVItemData("PowerNode7", ItemType.POWER_NODE),
	AVItemData("PowerNode8", ItemType.POWER_NODE),
	AVItemData("HealthNodeFragment1", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment2", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment3", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment4", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment5", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment6", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment7", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment8", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment9", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment10", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment11", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment12", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment13", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment14", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment15", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment16", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment17", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment18", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment19", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment20", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment21", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment22", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment23", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment24", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment25", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment26", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment27", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment28", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment29", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("HealthNodeFragment30", ItemType.HEALTH_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment1", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment2", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment3", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment4", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment5", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment6", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment7", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment8", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment9", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment10", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment11", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment12", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment13", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment14", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment15", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment16", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment17", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment18", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment19", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment20", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment21", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment22", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment23", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment24", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment25", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment26", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment27", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment28", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment29", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("PowerNodeFragment30", ItemType.POWER_NODE_FRAGMENT),
	AVItemData("RangeNode1", ItemType.RANGE_NODE),
	AVItemData("RangeNode2", ItemType.RANGE_NODE),
	AVItemData("RangeNode3", ItemType.RANGE_NODE),
	AVItemData("RangeNode4", ItemType.RANGE_NODE),
	AVItemData("SizeNode1", ItemType.SIZE_NODE),
	AVItemData("SizeNode2", ItemType.SIZE_NODE),
	AVItemData("SizeNode3", ItemType.SIZE_NODE),
	AVItemData("SizeNode4", ItemType.SIZE_NODE),
)
