import typing as t
from dataclasses import dataclass

from BaseClasses import ItemClassification

from .constants import AVItemType, AP_ID_BASE


@dataclass
class AVItemData:
    id: int
    name: str
    group_name: str
    ap_classification: ItemClassification
    is_default: bool

    def __post_init__(self):
        self.id += AP_ID_BASE


raw_item_data: t.Tuple[AVItemData] = (
    AVItemData(0, "Axiom Disruptor", AVItemType.WEAPON, ItemClassification.progression_skip_balancing, True),
    AVItemData(1, "Data Bomb", AVItemType.WEAPON, ItemClassification.progression_skip_balancing, True),
    AVItemData(2, "Firewall", AVItemType.WEAPON, ItemClassification.progression_skip_balancing, True),
    AVItemData(3, "Inertial Pulse", AVItemType.WEAPON, ItemClassification.progression_skip_balancing, True),
    AVItemData(4, "Ion Beam", AVItemType.WEAPON, ItemClassification.progression_skip_balancing, True),
    AVItemData(5, "Lightning Gun", AVItemType.WEAPON, ItemClassification.progression_skip_balancing, True),
    AVItemData(6, "Multi-Disruptor", AVItemType.WEAPON, ItemClassification.progression_skip_balancing, True),
    AVItemData(7, "Reflector", AVItemType.WEAPON, ItemClassification.progression_skip_balancing, True),
    AVItemData(8, "Shards", AVItemType.WEAPON, ItemClassification.progression_skip_balancing, True),
    AVItemData(9, "Quantum Variegator", AVItemType.WEAPON, ItemClassification.progression_skip_balancing, True),
    AVItemData(10, "Turbine Pulse", AVItemType.WEAPON, ItemClassification.progression_skip_balancing, True),
    AVItemData(11, "Voranj", AVItemType.WEAPON, ItemClassification.progression_skip_balancing, True),
    AVItemData(12, "Nova", AVItemType.WEAPON, ItemClassification.progression, True),
    AVItemData(13, "Tethered Charge", AVItemType.WEAPON, ItemClassification.progression_skip_balancing, True),
    AVItemData(14, "Hypo-Atomizer", AVItemType.WEAPON, ItemClassification.progression_skip_balancing, True),
    AVItemData(15, "Orbital Discharge", AVItemType.WEAPON, ItemClassification.progression_skip_balancing, True),
    AVItemData(16, "Distortion Field", AVItemType.WEAPON, ItemClassification.progression, True),
    AVItemData(17, "FlameThrower", AVItemType.WEAPON, ItemClassification.progression_skip_balancing, True),
    AVItemData(18, "Kilver", AVItemType.WEAPON, ItemClassification.progression, True),
    AVItemData(19, "Reverse Slicer", AVItemType.WEAPON, ItemClassification.progression, True),
    AVItemData(20, "Fat Beam", AVItemType.WEAPON, ItemClassification.progression_skip_balancing, True),
    AVItemData(21, "Heat Seeker", AVItemType.WEAPON, ItemClassification.progression_skip_balancing, True),
    AVItemData(22, "Scissor Beam", AVItemType.WEAPON, ItemClassification.progression_skip_balancing, True),
    AVItemData(23, "Address Disruptor 1", AVItemType.GLITCH, ItemClassification.progression, False),
    AVItemData(24, "Address Disruptor 2", AVItemType.GLITCH, ItemClassification.progression, False),
    AVItemData(25, "Laser Drill", AVItemType.DRILL, ItemClassification.progression, True),
    AVItemData(26, "Remote Drone", AVItemType.DRONE, ItemClassification.progression, False),
    AVItemData(27, "Address Bomb", AVItemType.GLITCH, ItemClassification.progression, False),
    AVItemData(28, "Grapple", AVItemType.MOVEMENT, ItemClassification.progression, True),
    AVItemData(29, "Field Disruptor", AVItemType.MOVEMENT, ItemClassification.progression, True),
    AVItemData(30, "Modified Lab Coat", AVItemType.COAT, ItemClassification.progression, False),
    AVItemData(31, "Trenchcoat", AVItemType.COAT, ItemClassification.progression, False),
    AVItemData(32, "Red Coat", AVItemType.COAT, ItemClassification.progression, False),
    AVItemData(33, "Sudran Key", AVItemType.KEY, ItemClassification.progression, True),
    AVItemData(34, "Enhanced Drone Launch", AVItemType.DRONE, ItemClassification.progression, False),
    AVItemData(35, "Drone Teleport", AVItemType.DRONE, ItemClassification.progression, True),
    AVItemData(36, "Passcode Tool", AVItemType.KEY, ItemClassification.progression, True),
    AVItemData(37, "Bioxflux Accelerator 1", AVItemType.TENDRILS, ItemClassification.filler, True),
    AVItemData(38, "Bioxflux Accelerator 2", AVItemType.TENDRILS, ItemClassification.filler, True),
    AVItemData(39, "Health Node", AVItemType.HEALTH_NODE, ItemClassification.useful, False),
    AVItemData(49, "Power Node 1", AVItemType.POWER_NODE, ItemClassification.useful, True),
    AVItemData(50, "Power Node 2", AVItemType.POWER_NODE, ItemClassification.useful, True),
    AVItemData(51, "Power Node 3", AVItemType.POWER_NODE, ItemClassification.useful, True),
    AVItemData(52, "Power Node 4", AVItemType.POWER_NODE, ItemClassification.useful, True),
    AVItemData(53, "Power Node 5", AVItemType.POWER_NODE, ItemClassification.useful, True),
    AVItemData(54, "Power Node 6", AVItemType.POWER_NODE, ItemClassification.useful, True),
    AVItemData(55, "Power Node 7", AVItemType.POWER_NODE, ItemClassification.useful, True),
    AVItemData(56, "Power Node 8", AVItemType.POWER_NODE, ItemClassification.useful, True),
    AVItemData(57, "Health Node Fragment 1", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(58, "Health Node Fragment 2", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(59, "Health Node Fragment 3", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(60, "Health Node Fragment 4", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(61, "Health Node Fragment 5", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(62, "Health Node Fragment 6", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(63, "Health Node Fragment 7", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(64, "Health Node Fragment 8", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(65, "Health Node Fragment 9", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(66, "Health Node Fragment 10", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(67, "Health Node Fragment 11", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(68, "Health Node Fragment 12", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(69, "Health Node Fragment 13", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(70, "Health Node Fragment 14", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(71, "Health Node Fragment 15", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(72, "Health Node Fragment 16", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(73, "Health Node Fragment 17", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(74, "Health Node Fragment 18", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(75, "Health Node Fragment 19", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(76, "Health Node Fragment 20", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(77, "Health Node Fragment 21", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(78, "Health Node Fragment 22", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(79, "Health Node Fragment 23", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(80, "Health Node Fragment 24", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(81, "Health Node Fragment 25", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(82, "Health Node Fragment 26", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(83, "Health Node Fragment 27", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(84, "Health Node Fragment 28", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(85, "Health Node Fragment 29", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(86, "Health Node Fragment 30", AVItemType.HEALTH_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(87, "Power Node Fragment 1", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(88, "Power Node Fragment 2", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(89, "Power Node Fragment 3", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(90, "Power Node Fragment 4", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(91, "Power Node Fragment 5", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(92, "Power Node Fragment 6", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(93, "Power Node Fragment 7", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(94, "Power Node Fragment 8", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(95, "Power Node Fragment 9", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(96, "Power Node Fragment 10", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(97, "Power Node Fragment 11", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(98, "Power Node Fragment 12", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(99, "Power Node Fragment 13", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(100, "Power Node Fragment 14", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(101, "Power Node Fragment 15", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(102, "Power Node Fragment 16", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(103, "Power Node Fragment 17", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(104, "Power Node Fragment 18", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(105, "Power Node Fragment 19", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(106, "Power Node Fragment 20", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(107, "Power Node Fragment 21", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(108, "Power Node Fragment 22", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(109, "Power Node Fragment 23", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(110, "Power Node Fragment 24", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(111, "Power Node Fragment 25", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(112, "Power Node Fragment 26", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(113, "Power Node Fragment 27", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(114, "Power Node Fragment 28", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(115, "Power Node Fragment 29", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(116, "Power Node Fragment 30", AVItemType.POWER_NODE_FRAGMENT, ItemClassification.useful, True),
    AVItemData(117, "Range Node 1", AVItemType.RANGE_NODE, ItemClassification.useful, True),
    AVItemData(118, "Range Node 2", AVItemType.RANGE_NODE, ItemClassification.useful, True),
    AVItemData(119, "Range Node 3", AVItemType.RANGE_NODE, ItemClassification.useful, True),
    AVItemData(120, "Range Node 4", AVItemType.RANGE_NODE, ItemClassification.useful, True),
    AVItemData(121, "Size Node 1", AVItemType.SIZE_NODE, ItemClassification.useful, True),
    AVItemData(122, "Size Node 2", AVItemType.SIZE_NODE, ItemClassification.useful, True),
    AVItemData(123, "Size Node 3", AVItemType.SIZE_NODE, ItemClassification.useful, True),
    AVItemData(124, "Size Node 4", AVItemType.SIZE_NODE, ItemClassification.useful, True),
    # Archipelago Progressive Items
    AVItemData(125, "Progressive Address Disruptor", AVItemType.GLITCH, ItemClassification.progression, False),
    AVItemData(126, "Progressive Coat", AVItemType.COAT, ItemClassification.progression, False),
    AVItemData(127, "Progressive Drone", AVItemType.DRONE, ItemClassification.progression, False),
)

item_data: t.Dict[str, AVItemData] = {data.name: data for data in raw_item_data}

ITEM_NAME_TO_ID: t.Dict[str, int] = {data.name: data.id for data in raw_item_data}
